---
- name: For Debian
  include: nginx_debian.yaml
  when: ansible_distribution  == 'Debian'

- name: For Centos
  include: nginx_centos.yaml
  when: ansible_distribution  == 'CentOS'

- name: check connection
  wait_for:
    host: "localhost"
    port: "80"
    state: started
    delay: 0
    timeout: 3
- name: url Check
  uri:
    url: http://localhost
    return_content: yes
  register: urlcheck
- debug:
    msg: "{{ urlcheck }}"
