---
- name: Apt update
 apt:
   update_cache: yes

- name: Redmine. Install packages
 apt:
   name: "{{ apt_redmine }}"
   state: latest

- name: MySQL. Setup
 block:
 - template:
     src: templates/.my.cnf
     dest: ~/.my.cnf
     owner: root
     mode: 0600
   notify:
     - mysql restart
- mysql_db:
   name: "{{ app_db_name }}"
   encoding: utf8

- mysql_user:
   name: "{{ app_db_user }}"
   password: "{{ app_db_pass }}"
   priv: "{{ app_db_name }}.*:ALL"

- name: RM. Clone
 git:
   repo: "{{ app_repo }}"
   dest: "{{ app_home }}"
   version: "{{ app_vers }}"
   accept_hostkey: yes

- name: RM. DB config
 template:
   src: database.yml.j2
   dest: "{{ app_home }}/config/database.yml"

- name: RM. Setup 01
 shell: |
   gem install bundler
   bundle update
 args:
   executable: /bin/bash
   chdir: "{{ app_home }}"

- name: RM. Secret generate
 shell: rake generate_secret_token
 args:
   chdir: "{{ app_home }}"
   creates: "{{ app_home }}/config/initializers/secret_token.rb"